### ISSUE TITLE
Value inserted out of bounds - crashes driver

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/node-homey-zwavedriver#2] opened 2016-08-03 08:05 UTC
When entering a value, e.g. 123123123 in one of the input fields and trying to commit this value. The Z-wave driver is crashing.

Expected result: No crash of Z-wave driver
Better expected result: Check values before submitting them (the min and max values of this number input had been set, so HTML5 form check before submit would do).

TypeError: value is out of bounds
    at checkInt (buffer.js:824:11)
    at Buffer.writeIntBE (buffer.js:956:5)
    at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:161:16
    at Array.forEach (native)
    at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:134:18)
    at /homey-app/manager/drivers.js:1:3459
    at ZwaveDriver.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:1:2049)
    at eventListeners.clientDriver (/homey-app/manager/drivers.js:1:2416)
    at /homey-app/helpers/client.js:1:868
    at Array.forEach (native)

--- INFO: com.fibaro has been killed ---

**Comment by RobinBol** [comment] 2016-09-21 13:15
This should be fixed by now, checked it and a try/catch was added around the writeIntBE() to catch out of bound values. Could not reproduce it either, so will close this issue. Thanks for reporting!

**Closed by RobinBol** 2016-09-21 13:15 UTC
