### ISSUE TITLE
[FEATURE ] CONFIGURATION.CONFIGURATION_GET

### ISSUE THREAD

**Issue by nattlip** [athombv/node-homey-zwavedriver#20] opened 2017-01-05 20:58 UTC
implement node.instance.CommandClass.COMMAND_CLASS_CONFIGURATION.CONFIGURATION_GET
to get config parameters from device in drivers to check the configuration parameters

**Comment by WeeJeWel** [comment] 2017-01-05 21:00
This is already possible?

**Comment by nattlip** [comment] 2017-01-05 21:05
could you give an example ?

**Comment by WeeJeWel** [comment] 2017-01-05 21:06
Just run what you typed, it should work :)

**Comment by nattlip** [comment] 2017-01-05 21:18
i'll try

**Comment by nattlip** [comment] 2017-01-05 21:30
then i get the sensor types of the device , i want the settings parameters of the device.

**Comment by nattlip** [comment] 2017-01-05 21:38
The Command Classes are documented extensively by Sigma Designs, and are freely available. 

Are all these commands implemented in the driver ?

**Comment by nattlip** [comment] 2017-01-08 07:43
i still cant get the parameter values of the zwave device . what is correct line of code in homey to get this ?

**Comment by caseda** [comment] 2017-01-08 19:59
`CONFIGURATION.CONFIGURATION_GET( 'Parameter Number', 3 )` is wrong anyway
should be `CONFIGURATION.CONFIGURATION_GET( {'Parameter Number': 3}, null )`

but anyway,
using the normal capability stilling (easier to implement)
have not found any device's that respond to the get,
it either timed out, (even for powered device)
gave a "SEND_SUCCESFULL_NO_ACK" (kinda like this anyway, probably because the device was asleep)
or just gave no response to the GET on report level

**Comment by TedTolboom** [comment] 2017-01-10 13:07
I can confirm @caseda 's feedback, also tried to get a specific parameter (to learn the actual default configuration and size of a parameter)... I was not able to get proper feedback of the device

**Comment by caseda** [comment] 2017-01-16 21:14
i already know why it is not reporting in debug on a GET, it is caught by the z-wave driver:
https://github.com/athombv/node-homey-zwavedriver/blob/master/lib/ZwaveDriver.js#L427

so it probably needs an extra tag or function check to also show it in debug.

**Comment by RobinBol** [comment] 2017-01-18 10:53
Is the problem that you can't see the `CONFIGURATION_GET` logging in the console? That is a very easy fix, just add a console log where @caseda refers to.

Or do I misunderstand this issue?

**Comment by RobinBol** [comment] 2017-02-22 13:19
Just tested:

```
		node.instance.CommandClass.COMMAND_CLASS_CONFIGURATION.CONFIGURATION_GET({ 'Parameter Number': 3 }, (err, result) => {
			console.log(err, result);
		});
```

The console log gives:
```
null { 'Parameter Number (Raw)': <Buffer 03>,
  'Parameter Number': 3,
  'Level (Raw)': <Buffer 01>,
  Level: { Size: 1 },
  'Configuration Value': <Buffer 01> }
```

I'll close this issue as the the `CONFIGURATION_GET` is implemented and working.

**Closed by RobinBol** 2017-02-22 13:19 UTC

**Comment by TedTolboom** [comment] 2017-02-22 14:20
@Robinbol

The solution mentioned will only work up to parameter 9... due to the definition that the GET command need to be provided in Hex values.
If provided as new buffer it will work for all parameter numbers:

                    // Option to retrieve configuration of a certain parameter upon wake-up; for debugging only
                 node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_GET( {'Parameter Number': new Buffer([10])}, (err, result) => {
console.log(err, result); 
  });

I will put some of the debugging command / functions I use on Github to share with the community.

**Comment by RobinBol** [comment] 2017-02-22 14:33
Oke great, thanks!
